import DashboardContainer from "@/components/dashboardLayout/dashboard/DashboardContainer";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    default: "Dashboard | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const DashboradPage = () => {
  return (
    <div>
      <DashboardContainer></DashboardContainer>
    </div>
  );
};

export default DashboradPage;
