import React from "react";
import MessagesContainer from "./components/MessagesContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Messages | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const page = () => {
  return <MessagesContainer />;
};

export default page;
