import PrivacyPolicyEditor from "@/components/dashboardLayout/privacy-policy/PrivacyPolicyEditor";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Privacy Policy | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const AboutPage = () => {
  return (
    <div>
      <h1 className='text-2xl font-bold w-full'>Privacy Policy</h1>
      <PrivacyPolicyEditor></PrivacyPolicyEditor>
    </div>
  );
};

export default AboutPage;
