import EarningContainer from "@/components/dashboardLayout/earning/EarningContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Earnings | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const EarningPage = () => {
  return (
    <div>
      <EarningContainer></EarningContainer>
    </div>
  );
};

export default EarningPage;
