import DeliveryQuoteProductContainer from "@/components/dashboardLayout/quote-management/[id]/deliveryQuoteProduct/DeliveryQuoteProductContainer";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    default: "Delivery Quote Product | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const DeliveryQuoteProductPage = () => {
  return <DeliveryQuoteProductContainer></DeliveryQuoteProductContainer>;
};

export default DeliveryQuoteProductPage;
