import SingleOrderDetailsContainer from "@/components/dashboardLayout/orderDetails/[id]/SingleOrderDetailsContainer";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    default: "Order Details | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const SingleOrderDetails = ({ params }: { params: { id: string } }) => {
  return (
    <div>
      <SingleOrderDetailsContainer id={params.id}></SingleOrderDetailsContainer>
    </div>
  );
};

export default SingleOrderDetails;
