import ProfileContainer from "@/components/dashboardLayout/profile/ProfileContainer";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    default: "Profile | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return (
    <div>
      <ProfileContainer></ProfileContainer>
    </div>
  );
};

export default ProfilePage;
