import OrderDetailsContainer from "@/components/dashboardLayout/orderDetails/OrderDetailsContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Order Details | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const OrderDetailsPage = () => {
  return (
    <div>
      <OrderDetailsContainer></OrderDetailsContainer>
    </div>
  );
};

export default OrderDetailsPage;
