import TermsEditor from "@/components/dashboardLayout/terms/TermsEditor";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Terms | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const TermsPage = () => {
  return (
    <div>
      <h1 className='text-2xl font-bold w-full'>Terms of Conditions</h1>
      <TermsEditor></TermsEditor>
    </div>
  );
};

export default TermsPage;
