import NotificationsContainer from "@/components/dashboardLayout/notifications/NotificationsContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Notifications | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const NotificationsPage = () => {
  return <NotificationsContainer></NotificationsContainer>;
};

export default NotificationsPage;
