import LibraryContainer from "@/components/library/LibraryContainer";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "Gallery | United Threads ",
    template: "%s | United Threads",
  },
  description: "Generated by create next app",
};

const page = () => {
  return (
    <div>
      <LibraryContainer />
    </div>
  );
};

export default page;
